//! `warden add-action`: generate a `.github/workflows/warden.yml` workflow
//! file that runs the warden GitHub Action against the repo's own workflows.
//!
//! Three operating modes:
//!
//!   1. **Print** (`--print`) — emit the workflow YAML to stdout, no writes.
//!      Lets users copy/paste the snippet into their existing CI setup.
//!   2. **Local write** (default, no `--pr`) — write `.github/workflows/warden.yml`
//!      directly to the current repo on disk. Errors if the file already
//!      exists; we never silently overwrite an existing warden install.
//!   3. **PR** (`--pr OWNER/REPO`) — push a branch to the user's fork (or to
//!      the upstream if they have write access) containing the new workflow
//!      file, and return either a compare URL (`--prepare-only`, default
//!      because it's safer) or open the PR for them.
//!
//! The workflow template generated by this module MUST pass warden's own
//! HIGH+ scan with zero findings. There is a self-compliance integration
//! test in `tests/add_action_test.rs` that re-scans the generated YAML
//! after every build to enforce this. If you change the template, run
//! `cargo test --release` and confirm the test still passes.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, bail, Context, Result};
use reqwest::blocking::Client;
use serde::Serialize;

use crate::fix;

/// Path of the workflow file we generate, relative to the repo root.
pub const WORKFLOW_PATH: &str = ".github/workflows/warden.yml";

/// Resolved SHA pin for `actions/checkout@v6.0.2`. Kept here so the template
/// is the single source of truth and `tests/add_action_test.rs` can verify
/// it stays in sync with `docs/src/...` and `examples/`.
pub const CHECKOUT_SHA: &str = "de0fac2e4500dabe0009e67214ff5f5447ce83dd";
pub const CHECKOUT_VERSION: &str = "v6.0.2";

/// Resolved SHA pin for `projectwarden/warden@v2.0.0`. Same source of truth
/// note as above. The release process must update this when a new warden
/// version ships. The SHA below is updated in the follow-up pin commit
/// after the v2.0.0 tag is cut.
pub const WARDEN_ACTION_SHA: &str = "a3c26c3f1897ddbe5c34cc3ce9ff4f14f84c83a8";
pub const WARDEN_ACTION_VERSION: &str = "v2.0.0";

/// Result of an add-action PR flow, mirrors the `fix --pr --format json`
/// output shape so the dashboard can consume it identically.
#[derive(Serialize)]
pub struct AddActionPrResult {
    pub pr_url: String,
    pub branch: Option<String>,
    pub workflow_path: String,
}

/// Generate the warden workflow YAML to add to a repo.
///
/// `fail_on` is the threshold the generated workflow uses for its CI gate
/// (`critical`, `high` (default), `medium`, `low`, or `none`). The function
/// rejects any other value so we can never emit a workflow that warden
/// itself wouldn't accept on its own command line.
pub fn generate_workflow_yaml(fail_on: &str) -> Result<String> {
    let normalized = fail_on.to_lowercase();
    if !matches!(
        normalized.as_str(),
        "critical" | "high" | "medium" | "low" | "none"
    ) {
        bail!(
            "invalid --fail-on value: '{fail_on}'. Expected one of: critical, high, medium, low, none."
        );
    }

    // The body is a hand-formatted YAML literal. Every action ref is
    // SHA-pinned with a trailing `# vX.Y.Z` comment so the template passes
    // WRD-311, WRD-332, WRD-333, and WRD-324. There is no risky trigger,
    // no run block (so no expression-injection surface), an explicit
    // `permissions: contents: read` block (with inline doc comment to
    // satisfy WRD-840), an explicit `concurrency:` block (WRD-842), and
    // `persist-credentials: false` on the checkout (WRD-730).
    //
    // We use a raw string literal so leading whitespace survives, and
    // assemble it with `String::replace` instead of `format!` so we don't
    // have to escape every `${{ ... }}` GitHub expression for the format
    // machinery.
    let template = r#"name: warden

# Run warden on every PR and on pushes to main. The action below scans
# .github/workflows/ for CI/CD security issues and fails the check if any
# finding at or above the configured severity is reported.
on:
  pull_request:
  push:
    branches: [main]

# Cancel in-progress runs on the same ref so duplicate pushes do not pile up.
concurrency:
  group: warden-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read   # repo checkout only, warden never needs write

jobs:
  scan:
    name: Scan workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@__CHECKOUT_SHA__  # __CHECKOUT_VER__
        with:
          persist-credentials: false

      - name: Run warden
        uses: projectwarden/warden@__WARDEN_SHA__  # __WARDEN_VER__
        with:
          fail-on: __FAIL_ON__
"#;

    let yaml = template
        .replace("__CHECKOUT_SHA__", CHECKOUT_SHA)
        .replace("__CHECKOUT_VER__", CHECKOUT_VERSION)
        .replace("__WARDEN_SHA__", WARDEN_ACTION_SHA)
        .replace("__WARDEN_VER__", WARDEN_ACTION_VERSION)
        .replace("__FAIL_ON__", &normalized);

    Ok(yaml)
}

/// Write the generated workflow file to `<repo_root>/.github/workflows/warden.yml`.
///
/// Refuses to overwrite an existing file: if the user already has a
/// `warden.yml` we want them to know they have one and decide what to do,
/// not silently clobber it.
pub fn write_workflow_file(repo_root: &Path, content: &str) -> Result<PathBuf> {
    if !repo_root.exists() {
        bail!("repo root does not exist: {}", repo_root.display());
    }
    if !repo_root.is_dir() {
        bail!("repo root is not a directory: {}", repo_root.display());
    }

    let workflows_dir = repo_root.join(".github").join("workflows");
    fs::create_dir_all(&workflows_dir)
        .with_context(|| format!("failed to create directory {}", workflows_dir.display()))?;

    let target = workflows_dir.join("warden.yml");
    if target.exists() {
        bail!(
            "{} already exists. Refusing to overwrite. Delete it first if you want to regenerate.",
            target.display()
        );
    }

    fs::write(&target, content).with_context(|| format!("failed to write {}", target.display()))?;

    Ok(target)
}

/// Open a PR (or prepare a branch and return a compare URL) that adds the
/// generated `warden.yml` to `owner/repo`. Mirrors `fix::open_fix_pr`'s
/// contract: when `prepare_only` is true (and `apply` is true), we push the
/// branch but stop short of POST /pulls so the user reviews on GitHub.
///
/// `plan_only` (= `!apply` from the CLI flag) prints what would happen but
/// makes no network calls. Used for dry runs and tests.
#[allow(clippy::too_many_arguments)]
pub fn open_add_action_pr(
    owner: &str,
    repo: &str,
    branch: Option<&str>,
    yaml: &str,
    fail_on: &str,
    token: Option<&str>,
    plan_only: bool,
    prepare_only: bool,
) -> Result<AddActionPrResult> {
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let branch_name = branch
        .map(|s| s.to_string())
        .unwrap_or_else(|| format!("warden/add-action-{ts}"));

    let title = "warden: add CI/CD security scanning workflow".to_string();
    let body = format!(
        "This PR was generated automatically by `warden add-action --pr`.\n\
\n\
## What this adds\n\
\n\
- New file: `{WORKFLOW_PATH}`\n\
- Runs the warden GitHub Action on every pull request and push to `main`\n\
- Fail threshold: `{fail_on}`\n\
- Scans `.github/workflows/` for CI/CD security issues (53 detection rules)\n\
\n\
## Why\n\
\n\
[warden](https://github.com/projectwarden/warden) catches expression injection, unpinned\n\
actions, missing permissions, supply-chain misconfigurations, and other GitHub\n\
Actions vulnerabilities before they ship. The configuration here is the\n\
recommended starter setup; you can tune `fail-on` or scope `paths:` later.\n\
\n\
---\n\
_generated by [warden](https://github.com/projectwarden/warden)_\n"
    );

    if plan_only {
        eprintln!(
            "[plan] Would {} against {}/{}",
            if prepare_only {
                "prepare branch (no PR)"
            } else {
                "create PR"
            },
            owner,
            repo
        );
        eprintln!("[plan] Branch: {branch_name}");
        eprintln!("[plan] Title: {title}");
        eprintln!("[plan] File:  {WORKFLOW_PATH}");
        let url = if prepare_only {
            format!("https://github.com/{owner}/{repo}/compare/PLAN...{branch_name}?expand=1")
        } else {
            format!("https://github.com/{owner}/{repo}/pull/PLAN (branch: {branch_name})")
        };
        return Ok(AddActionPrResult {
            pr_url: url,
            branch: Some(branch_name),
            workflow_path: WORKFLOW_PATH.to_string(),
        });
    }

    let token = token.ok_or_else(|| {
        anyhow!("--pr requires a GitHub token. Set GITHUB_TOKEN or pass --github-token.")
    })?;
    let client = fix::build_client(Some(token))?;
    let api = "https://api.github.com";

    // 1. Resolve default branch + check write access on upstream.
    let upstream_owner = owner.to_string();
    let upstream_repo = repo.to_string();
    let repo_url = format!("{api}/repos/{upstream_owner}/{upstream_repo}");
    let repo_info: fix::RepoInfo = client
        .get(&repo_url)
        .send()
        .with_context(|| format!("GET {repo_url}"))?
        .error_for_status()
        .with_context(|| "Failed to fetch repo info (check token scopes and repo slug)")?
        .json()
        .context("Failed to parse repo info JSON")?;
    let default_branch = repo_info.default_branch.clone();

    // 2. Decide whether to work on the upstream directly or on a fork.
    let has_push = repo_info
        .permissions
        .as_ref()
        .map(|p| p.push)
        .unwrap_or(false);
    let (work_owner, work_repo) = if has_push {
        (upstream_owner.clone(), upstream_repo.clone())
    } else {
        eprintln!(
            "No write access to {upstream_owner}/{upstream_repo}. Forking under your account..."
        );
        let (fo, fr) = fix::fork_and_wait(&client, api, &upstream_owner, &upstream_repo)?;
        eprintln!("Fork ready: {fo}/{fr}");
        (fo, fr)
    };

    // 3. Get the default-branch tip SHA on the working repo.
    let final_branch = create_branch(
        &client,
        api,
        &work_owner,
        &work_repo,
        &default_branch,
        &branch_name,
        ts,
    )?;

    // 4. Commit the generated workflow file via the Contents API.
    commit_new_file(
        &client,
        api,
        &work_owner,
        &work_repo,
        &default_branch,
        &final_branch,
        WORKFLOW_PATH,
        yaml,
    )?;

    // 5. Either open the PR or return a compare URL.
    if prepare_only {
        let url = if work_owner != upstream_owner {
            format!(
                "https://github.com/{upstream_owner}/{upstream_repo}/compare/{default_branch}...{work_owner}:{final_branch}?expand=1"
            )
        } else {
            format!(
                "https://github.com/{upstream_owner}/{upstream_repo}/compare/{default_branch}...{final_branch}?expand=1"
            )
        };
        return Ok(AddActionPrResult {
            pr_url: url,
            branch: Some(final_branch),
            workflow_path: WORKFLOW_PATH.to_string(),
        });
    }

    let pr_url = format!("{api}/repos/{upstream_owner}/{upstream_repo}/pulls");
    let head = if work_owner != upstream_owner {
        format!("{work_owner}:{final_branch}")
    } else {
        final_branch.clone()
    };
    let pr_body = serde_json::json!({
        "title": title,
        "head": head,
        "base": default_branch,
        "body": body,
    });
    let pr: fix::PullRequestResp = client
        .post(&pr_url)
        .json(&pr_body)
        .send()
        .with_context(|| format!("POST {pr_url}"))?
        .error_for_status()
        .context("Failed to open pull request")?
        .json()
        .context("Failed to parse PR response")?;

    Ok(AddActionPrResult {
        pr_url: pr.html_url,
        branch: Some(final_branch),
        workflow_path: WORKFLOW_PATH.to_string(),
    })
}

/// Create a new branch on `work_owner/work_repo` from the tip of
/// `default_branch`. Retries with a numeric suffix on 422 collisions.
fn create_branch(
    client: &Client,
    api: &str,
    work_owner: &str,
    work_repo: &str,
    default_branch: &str,
    branch_name: &str,
    ts: u64,
) -> Result<String> {
    let ref_url = format!("{api}/repos/{work_owner}/{work_repo}/git/ref/heads/{default_branch}");
    let base_ref: fix::GitRef = client
        .get(&ref_url)
        .send()
        .with_context(|| format!("GET {ref_url}"))?
        .error_for_status()
        .with_context(|| format!("Failed to read ref heads/{default_branch}"))?
        .json()
        .context("Failed to parse ref JSON")?;
    let base_sha = base_ref.object.sha;

    let create_ref_url = format!("{api}/repos/{work_owner}/{work_repo}/git/refs");
    let mut final_branch = branch_name.to_string();
    for attempt in 0..3u32 {
        let candidate = if attempt == 0 {
            final_branch.clone()
        } else {
            format!("{branch_name}-{}", ts.wrapping_add(attempt as u64))
        };
        let body = serde_json::json!({
            "ref": format!("refs/heads/{}", candidate),
            "sha": base_sha,
        });
        let resp = client
            .post(&create_ref_url)
            .json(&body)
            .send()
            .with_context(|| format!("POST {create_ref_url}"))?;
        let status = resp.status();
        if status.is_success() {
            final_branch = candidate;
            return Ok(final_branch);
        }
        if status.as_u16() == 422 {
            if attempt == 2 {
                bail!("Could not create a unique branch after 3 attempts");
            }
            continue;
        }
        let txt = resp.text().unwrap_or_default();
        bail!("Failed to create branch ref: HTTP {status} {txt}");
    }
    Ok(final_branch)
}

/// PUT a brand-new file (no existing SHA) to the working branch via the
/// GitHub Contents API. We deliberately do NOT lookup-and-merge an existing
/// file: `add-action` is for repos that don't already have warden installed,
/// and the local-mode `write_workflow_file` already errors on existing
/// files.
#[allow(clippy::too_many_arguments)]
fn commit_new_file(
    client: &Client,
    api: &str,
    work_owner: &str,
    work_repo: &str,
    default_branch: &str,
    branch: &str,
    path: &str,
    content: &str,
) -> Result<()> {
    let contents_url = format!("{api}/repos/{work_owner}/{work_repo}/contents/{path}");

    // Refuse to overwrite an existing file even on the remote: if a
    // workflow with this exact name already exists, the user already has
    // warden (or another tool) installed and we should not silently
    // clobber it. Probe with a GET against the BASE branch (not our new
    // branch which doesn't have it yet).
    let probe = client
        .get(&contents_url)
        .query(&[("ref", default_branch)])
        .send();
    if let Ok(resp) = probe {
        if resp.status().is_success() {
            bail!(
                "{path} already exists in {work_owner}/{work_repo} on the {default_branch} branch. Refusing to overwrite."
            );
        }
    }

    let put_body = serde_json::json!({
        "message": "warden: add CI/CD security scanning workflow",
        "content": fix::base64_encode(content.as_bytes()),
        "branch": branch,
    });
    let resp = client
        .put(&contents_url)
        .json(&put_body)
        .send()
        .with_context(|| format!("PUT {contents_url}"))?;
    if !resp.status().is_success() {
        let status = resp.status();
        let txt = resp.text().unwrap_or_default();
        bail!("Failed to commit {path}: HTTP {status} {txt}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_yaml_default_high() {
        let y = generate_workflow_yaml("high").unwrap();
        assert!(y.contains("fail-on: high"));
        assert!(y.contains("name: warden"));
        assert!(y.contains("persist-credentials: false"));
        assert!(y.contains("concurrency:"));
        assert!(y.contains("contents: read"));
    }

    #[test]
    fn generate_yaml_normalizes_case() {
        let y = generate_workflow_yaml("HIGH").unwrap();
        assert!(y.contains("fail-on: high"));
    }

    #[test]
    fn generate_yaml_rejects_invalid_fail_on() {
        let err = generate_workflow_yaml("warning").unwrap_err();
        assert!(err.to_string().contains("invalid --fail-on"));
    }

    #[test]
    fn generate_yaml_pins_both_actions_to_sha() {
        let y = generate_workflow_yaml("high").unwrap();
        assert!(y.contains(&format!("actions/checkout@{CHECKOUT_SHA}")));
        assert!(y.contains(&format!("projectwarden/warden@{WARDEN_ACTION_SHA}")));
        assert!(y.contains(&format!("# {CHECKOUT_VERSION}")));
        assert!(y.contains(&format!("# {WARDEN_ACTION_VERSION}")));
    }

    #[test]
    fn generate_yaml_respects_fail_on_value() {
        for level in ["critical", "high", "medium", "low", "none"] {
            let y = generate_workflow_yaml(level).unwrap();
            assert!(
                y.contains(&format!("fail-on: {level}")),
                "expected fail-on: {level} in output"
            );
        }
    }

    #[test]
    fn write_workflow_file_creates_dir_chain() {
        let tmp = tempdir();
        let path = write_workflow_file(&tmp, "name: warden\n").unwrap();
        assert!(path.ends_with(".github/workflows/warden.yml"));
        assert!(path.exists());
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn write_workflow_file_errors_when_target_exists() {
        let tmp = tempdir();
        write_workflow_file(&tmp, "first").unwrap();
        let err = write_workflow_file(&tmp, "second").unwrap_err();
        assert!(err.to_string().contains("already exists"));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    fn tempdir() -> PathBuf {
        let p = std::env::temp_dir().join(format!(
            "warden-add-action-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::create_dir_all(&p).unwrap();
        p
    }
}
